const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

var routes = require('./routes/routes.js')
var routesLogin = require('./routes/login.js')
var routesUser = require('./routes/user.js')
var routesPoolType = require('./routes/poolType.js')
var routesFilterType = require('./routes/filterType.js')
var routesPayType = require('./routes/payType.js')
var routesUnitedMeasured = require('./routes/unitedMeasured.js')
var routesSupplies = require('./routes/supplies.js')
var routesRole = require('./routes/role.js')
var routesIdClientType = require('./routes/idClientType.js')
var routesClientType = require('./routes/clientType.js')
var routesPoolType = require('./routes/pooltype.js')
var routesFilterType = require('./routes/filtertype.js')
var routesPayType = require('./routes/paytype.js')
var routesCountry = require('./routes/country.js')
var routesState = require('./routes/state.js')
var routesCity = require('./routes/city.js')
var routesMoneyType = require('./routes/moneyType.js');
var routesCustomer = require('./routes/Customer.js');
var routesCustomerPool = require('./routes/PoolCustomer.js')

var mySqlConnection = require('./connection.js')
var cors = require('cors')



express()
  .use(cors())
  .use(express.json())
  .use(express.urlencoded({extended: true}))
  .use(routes)
  .use(routesLogin)
  .use(routesUser)
  .use(routesPoolType)
  .use(routesFilterType)
  .use(routesPayType)
  .use(routesUnitedMeasured)
  .use(routesSupplies)
  .use(routesRole)
  .use(routesIdClientType)
  .use(routesClientType)
  .use(express.json())
  .use(routesCountry)
  .use(routesState)
  .use(routesCity)
  .use(routesMoneyType)
  .use(routesCustomer)
  .use(routesCustomerPool)
  
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
